name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.VERSION_TOKEN }}
      - run: git config --global user.name 'Jonathan'
      - run: git config --global user.email 'koffeinmissbrukarn@gmail.com'
      - name: Check commit message
        id: check_commit
        run: echo "should_increment=$(echo "${{ github.event.head_commit.message }}" | grep -cE '^\[RELEASE\]')" >> $GITHUB_ENV
      - name: Increment version
        run: |
          if [[ ${{ steps.check_commit.outputs.should_increment }} -eq 0 ]]; then
            npm version patch -m "[RELEASE] %s"
            git push
          else
            echo "Commit message starts with [RELEASE], skipping version increment."
          fi